name: octoread_pages
description: Pages app (frontend app example) for OctoRead
version: 0.0.1
author: Anar K. Jafarov <anar.k.jafarov@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0